d1 = float(input('Digite o diametro um: '))
d2 = float(input('Digite o diametro dois: '))
a = (d1*d2)
print ('A área dos diametros um e dois é igual a {:.1f}m²'.format(a))
print ('Será necessario {:.1f} baldes para pintar essa área!'.format(a/2))
